/* Os_tc39xx.h - Description of Tricore TC39XX (Aurix development vehicle)
 *
 * CHECK: TABS 4 (see editor commands at end of file)
 *
 * Copyright Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 *
 * $Id: Os_tc39xx.h 1.1 2017/12/21 16:34:56CET Postolache, Alexandru (uidu6496) none  $
*/

/*	This file describes the TC39XX variant of Tricore.
*/

#ifndef OS_TC39XX_H
#define OS_TC39XX_H

/*	Setup architecture */

#define OS_TRICOREARCH	OS_TRICOREARCH_162

/* number of cores available on this derivative */
#define OS_N_CORES_MAX				6

/*	Tricore CPU Core SFRs
*/
#include <TRICORE/Os_TRICORE_core.h>

/* Start adress of physical address space */
#define OS_PHYS_ADDR_SPACE_START	OS_U(0x10000000)

/* Base addresses for the memory mapped CSFRs needed for StartCore()
 * 
 * Core 0: F881 0000
 * Core 1: F883 0000
 * Core 2: F885 0000
 * Core 3: F887 0000
 * Core 4: F889 0000
 * Core 5: F88D 0000 (!)
 *
 * */
#define OS_CPUCSFR(coreid) \
	(((coreid)<5) ? (OS_U(0xF8810000) + ((coreid)*OS_U(0x20000))) : OS_U(0xF88D0000))

/* Core-specific physical memory attributes for data(PMA0)/instruction(PMA1) cache enabled/disabled
 *
 * The TC1.6.2 cores have true caches, which we cannot use for writeable memories since there is
 * no way to achieve cache coherency (in an atomic fashion).
 *
 * PMA values:
 * Segment:  fedc ba98 7654 3210
 *           0000 0011 0000 0000 - 0x0300 - cached access on segments which are cached by default.
 */
#define OS_PMA0_CACHEENABLED(coreid) OS_U(0x0300)
#define OS_PMA0_CACHEDISABLED(coreid) OS_U(0x0300)
#define OS_PMA1_CACHEENABLED(coreid) OS_PMA0_CACHEENABLED(coreid)
#define OS_PMA1_CACHEDISABLED(coreid) OS_U(0x0300)
#define PCON0_CACHE_BYPASS OS_U(0x2)
#define DCON0_CACHE_BYPASS OS_U(0x2)

/* Memory protection registers don't have lower 3 bits in Aurix
*/
#define OS_DPRX_GRANULARITY_BITS	3u

/* 
 * This list is derived from the A-step target specification.
 */

#define OS_SRCBASE  OS_U(0xf0038000)

#define OS_SRC_CPU0SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0000))
#define OS_SRC_CPU1SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0004))
#define OS_SRC_CPU2SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0008))
#define OS_SRC_CPU3SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x000C))
#define OS_SRC_CPU4SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0010))
#define OS_SRC_CPU5SB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0014))
#define OS_SRC_BCUSPB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0020))
#define OS_SRC_BCUBBB (*(os_tricoresrn_t *)(OS_SRCBASE+0x0024))
#define OS_SRC_AGBT (*(os_tricoresrn_t *)(OS_SRCBASE+0x002C))
#define OS_SRC_XBAR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0030))
#define OS_SRC_XBAR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0034))
#define OS_SRC_XBAR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0038))
#define OS_SRC_CERBERUS0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0040))
#define OS_SRC_CERBERUS1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0044))
#define OS_SRC_ASCLIN0TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0050))
#define OS_SRC_ASCLIN1TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x005C))
#define OS_SRC_ASCLIN2TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0068))
#define OS_SRC_ASCLIN3TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0074))
#define OS_SRC_ASCLIN4TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0080))
#define OS_SRC_ASCLIN5TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x008C))
#define OS_SRC_ASCLIN6TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0098))
#define OS_SRC_ASCLIN7TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00A4))
#define OS_SRC_ASCLIN0RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0054))
#define OS_SRC_ASCLIN1RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0060))
#define OS_SRC_ASCLIN2RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x006C))
#define OS_SRC_ASCLIN3RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0078))
#define OS_SRC_ASCLIN4RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0084))
#define OS_SRC_ASCLIN5RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0090))
#define OS_SRC_ASCLIN6RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x009C))
#define OS_SRC_ASCLIN7RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00A8))
#define OS_SRC_ASCLIN0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0058))
#define OS_SRC_ASCLIN1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0064))
#define OS_SRC_ASCLIN2ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0070))
#define OS_SRC_ASCLIN3ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x007C))
#define OS_SRC_ASCLIN4ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0088))
#define OS_SRC_ASCLIN5ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0094))
#define OS_SRC_ASCLIN6ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x00A0))
#define OS_SRC_ASCLIN7ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x00AC))
#define OS_SRC_MTUDONE (*(os_tricoresrn_t *)(OS_SRCBASE+0x00BC))
#define OS_SRC_QSPI0TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00C0))
#define OS_SRC_QSPI1TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00D4))
#define OS_SRC_QSPI2TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00E8))
#define OS_SRC_QSPI3TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00FC))
#define OS_SRC_QSPI4TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0110))
#define OS_SRC_QSPI5TX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0124))
#define OS_SRC_QSPI0RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00C4))
#define OS_SRC_QSPI1RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00D8))
#define OS_SRC_QSPI2RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x00EC))
#define OS_SRC_QSPI3RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0100))
#define OS_SRC_QSPI4RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0114))
#define OS_SRC_QSPI5RX (*(os_tricoresrn_t *)(OS_SRCBASE+0x0128))
#define OS_SRC_QSPI0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x00C8))
#define OS_SRC_QSPI1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x00DC))
#define OS_SRC_QSPI2ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x00F0))
#define OS_SRC_QSPI3ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0104))
#define OS_SRC_QSPI4ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0118))
#define OS_SRC_QSPI5ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x012C))
#define OS_SRC_QSPI0PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x00CC))
#define OS_SRC_QSPI1PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x00E0))
#define OS_SRC_QSPI2PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x00F4))
#define OS_SRC_QSPI3PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x0108))
#define OS_SRC_QSPI4PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x011C))
#define OS_SRC_QSPI5PT (*(os_tricoresrn_t *)(OS_SRCBASE+0x0130))
#define OS_SRC_QSPI0U (*(os_tricoresrn_t *)(OS_SRCBASE+0x00D0))
#define OS_SRC_QSPI1U (*(os_tricoresrn_t *)(OS_SRCBASE+0x00E4))
#define OS_SRC_QSPI2U (*(os_tricoresrn_t *)(OS_SRCBASE+0x00F8))
#define OS_SRC_QSPI3U (*(os_tricoresrn_t *)(OS_SRCBASE+0x010C))
#define OS_SRC_QSPI4U (*(os_tricoresrn_t *)(OS_SRCBASE+0x0120))
#define OS_SRC_QSPI5U (*(os_tricoresrn_t *)(OS_SRCBASE+0x0134))
#define OS_SRC_QSPI2HC (*(os_tricoresrn_t *)(OS_SRCBASE+0x0158))
#define OS_SRC_QSPI3HC (*(os_tricoresrn_t *)(OS_SRCBASE+0x015C))
#define OS_SRC_HSCT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0160))
#define OS_SRC_HSCT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0164))
#define OS_SRC_HSSL0COK0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0170))
#define OS_SRC_HSSL0COK1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0180))
#define OS_SRC_HSSL0COK2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0190))
#define OS_SRC_HSSL0COK3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01A0))
#define OS_SRC_HSSL0RDI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0174))
#define OS_SRC_HSSL0RDI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0184))
#define OS_SRC_HSSL0RDI2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0194))
#define OS_SRC_HSSL0RDI3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01A4))
#define OS_SRC_HSSL0ERR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0178))
#define OS_SRC_HSSL0ERR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0188))
#define OS_SRC_HSSL0ERR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0198))
#define OS_SRC_HSSL0ERR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01A8))
#define OS_SRC_HSSL0TRG0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x017C))
#define OS_SRC_HSSL0TRG1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x018C))
#define OS_SRC_HSSL0TRG2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x019C))
#define OS_SRC_HSSL0TRG3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01AC))
#define OS_SRC_HSSL0EXI (*(os_tricoresrn_t *)(OS_SRCBASE+0x01B0))
#define OS_SRC_HSSL1COK0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01B4))
#define OS_SRC_HSSL1COK1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01C4))
#define OS_SRC_HSSL1COK2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01D4))
#define OS_SRC_HSSL1COK3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01E4))
#define OS_SRC_HSSL1RDI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01B8))
#define OS_SRC_HSSL1RDI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01C8))
#define OS_SRC_HSSL1RDI2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01D8))
#define OS_SRC_HSSL1RDI3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01E8))
#define OS_SRC_HSSL1ERR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01BC))
#define OS_SRC_HSSL1ERR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01CC))
#define OS_SRC_HSSL1ERR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01DC))
#define OS_SRC_HSSL1ERR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01EC))
#define OS_SRC_HSSL1TRG0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01C0))
#define OS_SRC_HSSL1TRG1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01D0))
#define OS_SRC_HSSL1TRG2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01E0))
#define OS_SRC_HSSL1TRG3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x01F0))
#define OS_SRC_HSSL1EXI (*(os_tricoresrn_t *)(OS_SRCBASE+0x01F4))
#define OS_SRC_I2C0DTR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0200))
#define OS_SRC_I2C0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0204))
#define OS_SRC_I2C0P (*(os_tricoresrn_t *)(OS_SRCBASE+0x0208))
#define OS_SRC_I2C1DTR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0210))
#define OS_SRC_I2C1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0214))
#define OS_SRC_I2C1P (*(os_tricoresrn_t *)(OS_SRCBASE+0x0218))
#define OS_SRC_SENT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0220))
#define OS_SRC_SENT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0224))
#define OS_SRC_SENT2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0228))
#define OS_SRC_SENT3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x022C))
#define OS_SRC_SENT4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0230))
#define OS_SRC_SENT5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0234))
#define OS_SRC_SENT6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0238))
#define OS_SRC_SENT7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x023C))
#define OS_SRC_SENT8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0240))
#define OS_SRC_SENT9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0244))
#define OS_SRC_MSC0SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0250))
#define OS_SRC_MSC1SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0264))
#define OS_SRC_MSC2SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0278))
#define OS_SRC_MSC3SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x028C))
#define OS_SRC_MSC0SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0254))
#define OS_SRC_MSC1SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0268))
#define OS_SRC_MSC2SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x027C))
#define OS_SRC_MSC3SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0290))
#define OS_SRC_MSC0SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0258))
#define OS_SRC_MSC1SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x026C))
#define OS_SRC_MSC2SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0280))
#define OS_SRC_MSC3SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0294))
#define OS_SRC_MSC0SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x025C))
#define OS_SRC_MSC1SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0270))
#define OS_SRC_MSC2SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0284))
#define OS_SRC_MSC3SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0298))
#define OS_SRC_MSC0SR4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0260))
#define OS_SRC_MSC1SR4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0274))
#define OS_SRC_MSC2SR4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0288))
#define OS_SRC_MSC3SR4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x029C))
#define OS_SRC_CCU60SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02A0))
#define OS_SRC_CCU61SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02B0))
#define OS_SRC_CCU60SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02A4))
#define OS_SRC_CCU61SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02B4))
#define OS_SRC_CCU60SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02A8))
#define OS_SRC_CCU61SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02B8))
#define OS_SRC_CCU60SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02AC))
#define OS_SRC_CCU61SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02BC))
#define OS_SRC_GPT120CIRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x02E0))
#define OS_SRC_GPT120T2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02E4))
#define OS_SRC_GPT120T3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02E8))
#define OS_SRC_GPT120T4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02EC))
#define OS_SRC_GPT120T5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02F0))
#define OS_SRC_GPT120T6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x02F4))
#define OS_SRC_STM0SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0300))
#define OS_SRC_STM1SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0308))
#define OS_SRC_STM2SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0310))
#define OS_SRC_STM3SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0318))
#define OS_SRC_STM4SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0320))
#define OS_SRC_STM5SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0328))
#define OS_SRC_STM0SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0304))
#define OS_SRC_STM1SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x030C))
#define OS_SRC_STM2SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0314))
#define OS_SRC_STM3SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x031C))
#define OS_SRC_STM4SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0324))
#define OS_SRC_STM5SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x032C))
#define OS_SRC_FCE0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0330))
#define OS_SRC_DMAERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0340))
#define OS_SRC_DMACH0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0350))
#define OS_SRC_DMACH1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0354))
#define OS_SRC_DMACH2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0358))
#define OS_SRC_DMACH3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x035C))
#define OS_SRC_DMACH4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0360))
#define OS_SRC_DMACH5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0364))
#define OS_SRC_DMACH6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0368))
#define OS_SRC_DMACH7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x036C))
#define OS_SRC_DMACH8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0370))
#define OS_SRC_DMACH9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0374))
#define OS_SRC_DMACH10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0378))
#define OS_SRC_DMACH11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x037C))
#define OS_SRC_DMACH12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0380))
#define OS_SRC_DMACH13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0384))
#define OS_SRC_DMACH14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0388))
#define OS_SRC_DMACH15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x038C))
#define OS_SRC_DMACH16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0390))
#define OS_SRC_DMACH17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0394))
#define OS_SRC_DMACH18 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0398))
#define OS_SRC_DMACH19 (*(os_tricoresrn_t *)(OS_SRCBASE+0x039C))
#define OS_SRC_DMACH20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03A0))
#define OS_SRC_DMACH21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03A4))
#define OS_SRC_DMACH22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03A8))
#define OS_SRC_DMACH23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03AC))
#define OS_SRC_DMACH24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03B0))
#define OS_SRC_DMACH25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03B4))
#define OS_SRC_DMACH26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03B8))
#define OS_SRC_DMACH27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03BC))
#define OS_SRC_DMACH28 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03C0))
#define OS_SRC_DMACH29 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03C4))
#define OS_SRC_DMACH30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03C8))
#define OS_SRC_DMACH31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03CC))
#define OS_SRC_DMACH32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03D0))
#define OS_SRC_DMACH33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03D4))
#define OS_SRC_DMACH34 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03D8))
#define OS_SRC_DMACH35 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03DC))
#define OS_SRC_DMACH36 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03E0))
#define OS_SRC_DMACH37 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03E4))
#define OS_SRC_DMACH38 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03E8))
#define OS_SRC_DMACH39 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03EC))
#define OS_SRC_DMACH40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03F0))
#define OS_SRC_DMACH41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03F4))
#define OS_SRC_DMACH42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03F8))
#define OS_SRC_DMACH43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x03FC))
#define OS_SRC_DMACH44 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0400))
#define OS_SRC_DMACH45 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0404))
#define OS_SRC_DMACH46 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0408))
#define OS_SRC_DMACH47 (*(os_tricoresrn_t *)(OS_SRCBASE+0x040C))
#define OS_SRC_DMACH48 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0410))
#define OS_SRC_DMACH49 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0414))
#define OS_SRC_DMACH50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0418))
#define OS_SRC_DMACH51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x041C))
#define OS_SRC_DMACH52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0420))
#define OS_SRC_DMACH53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0424))
#define OS_SRC_DMACH54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0428))
#define OS_SRC_DMACH55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x042C))
#define OS_SRC_DMACH56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0430))
#define OS_SRC_DMACH57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0434))
#define OS_SRC_DMACH58 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0438))
#define OS_SRC_DMACH59 (*(os_tricoresrn_t *)(OS_SRCBASE+0x043C))
#define OS_SRC_DMACH60 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0440))
#define OS_SRC_DMACH61 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0444))
#define OS_SRC_DMACH62 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0448))
#define OS_SRC_DMACH63 (*(os_tricoresrn_t *)(OS_SRCBASE+0x044C))
#define OS_SRC_DMACH64 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0450))
#define OS_SRC_DMACH65 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0454))
#define OS_SRC_DMACH66 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0458))
#define OS_SRC_DMACH67 (*(os_tricoresrn_t *)(OS_SRCBASE+0x045C))
#define OS_SRC_DMACH68 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0460))
#define OS_SRC_DMACH69 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0464))
#define OS_SRC_DMACH70 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0468))
#define OS_SRC_DMACH71 (*(os_tricoresrn_t *)(OS_SRCBASE+0x046C))
#define OS_SRC_DMACH72 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0470))
#define OS_SRC_DMACH73 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0474))
#define OS_SRC_DMACH74 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0478))
#define OS_SRC_DMACH75 (*(os_tricoresrn_t *)(OS_SRCBASE+0x047C))
#define OS_SRC_DMACH76 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0480))
#define OS_SRC_DMACH77 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0484))
#define OS_SRC_DMACH78 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0488))
#define OS_SRC_DMACH79 (*(os_tricoresrn_t *)(OS_SRCBASE+0x048C))
#define OS_SRC_DMACH80 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0490))
#define OS_SRC_DMACH81 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0494))
#define OS_SRC_DMACH82 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0498))
#define OS_SRC_DMACH83 (*(os_tricoresrn_t *)(OS_SRCBASE+0x049C))
#define OS_SRC_DMACH84 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04A0))
#define OS_SRC_DMACH85 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04A4))
#define OS_SRC_DMACH86 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04A8))
#define OS_SRC_DMACH87 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04AC))
#define OS_SRC_DMACH88 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04B0))
#define OS_SRC_DMACH89 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04B4))
#define OS_SRC_DMACH90 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04B8))
#define OS_SRC_DMACH91 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04BC))
#define OS_SRC_DMACH92 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04C0))
#define OS_SRC_DMACH93 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04C4))
#define OS_SRC_DMACH94 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04C8))
#define OS_SRC_DMACH95 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04CC))
#define OS_SRC_DMACH96 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04D0))
#define OS_SRC_DMACH97 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04D4))
#define OS_SRC_DMACH98 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04D8))
#define OS_SRC_DMACH99 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04DC))
#define OS_SRC_DMACH100 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04E0))
#define OS_SRC_DMACH101 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04E4))
#define OS_SRC_DMACH102 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04E8))
#define OS_SRC_DMACH103 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04EC))
#define OS_SRC_DMACH104 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04F0))
#define OS_SRC_DMACH105 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04F4))
#define OS_SRC_DMACH106 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04F8))
#define OS_SRC_DMACH107 (*(os_tricoresrn_t *)(OS_SRCBASE+0x04FC))
#define OS_SRC_DMACH108 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0500))
#define OS_SRC_DMACH109 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0504))
#define OS_SRC_DMACH110 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0508))
#define OS_SRC_DMACH111 (*(os_tricoresrn_t *)(OS_SRCBASE+0x050C))
#define OS_SRC_DMACH112 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0510))
#define OS_SRC_DMACH113 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0514))
#define OS_SRC_DMACH114 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0518))
#define OS_SRC_DMACH115 (*(os_tricoresrn_t *)(OS_SRCBASE+0x051C))
#define OS_SRC_DMACH116 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0520))
#define OS_SRC_DMACH117 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0524))
#define OS_SRC_DMACH118 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0528))
#define OS_SRC_DMACH119 (*(os_tricoresrn_t *)(OS_SRCBASE+0x052C))
#define OS_SRC_DMACH120 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0530))
#define OS_SRC_DMACH121 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0534))
#define OS_SRC_DMACH122 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0538))
#define OS_SRC_DMACH123 (*(os_tricoresrn_t *)(OS_SRCBASE+0x053C))
#define OS_SRC_DMACH124 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0540))
#define OS_SRC_DMACH125 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0544))
#define OS_SRC_DMACH126 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0548))
#define OS_SRC_DMACH127 (*(os_tricoresrn_t *)(OS_SRCBASE+0x054C))
#define OS_SRC_PDMAERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0550))
#define OS_SRC_PDMARDY (*(os_tricoresrn_t *)(OS_SRCBASE+0x0554))
#define OS_SRC_ETH (*(os_tricoresrn_t *)(OS_SRCBASE+0x0560))
#define OS_SRC_CAN0INT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0580))
#define OS_SRC_CAN0INT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0584))
#define OS_SRC_CAN0INT2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0588))
#define OS_SRC_CAN0INT3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x058C))
#define OS_SRC_CAN0INT4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0590))
#define OS_SRC_CAN0INT5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0594))
#define OS_SRC_CAN0INT6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0598))
#define OS_SRC_CAN0INT7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x059C))
#define OS_SRC_CAN0INT8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05A0))
#define OS_SRC_CAN0INT9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05A4))
#define OS_SRC_CAN0INT10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05A8))
#define OS_SRC_CAN0INT11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05AC))
#define OS_SRC_CAN0INT12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05B0))
#define OS_SRC_CAN0INT13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05B4))
#define OS_SRC_CAN0INT14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05B8))
#define OS_SRC_CAN0INT15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05BC))
#define OS_SRC_CAN1INT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05C0))
#define OS_SRC_CAN1INT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05C4))
#define OS_SRC_CAN1INT2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05C8))
#define OS_SRC_CAN1INT3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05CC))
#define OS_SRC_CAN1INT4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05D0))
#define OS_SRC_CAN1INT5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05D4))
#define OS_SRC_CAN1INT6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05D8))
#define OS_SRC_CAN1INT7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05DC))
#define OS_SRC_CAN1INT8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05E0))
#define OS_SRC_CAN1INT9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05E4))
#define OS_SRC_CAN1INT10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05E8))
#define OS_SRC_CAN1INT11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05EC))
#define OS_SRC_CAN1INT12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05F0))
#define OS_SRC_CAN1INT13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05F4))
#define OS_SRC_CAN1INT14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05F8))
#define OS_SRC_CAN1INT15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x05FC))
#define OS_SRC_CAN2INT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0600))
#define OS_SRC_CAN2INT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0604))
#define OS_SRC_CAN2INT2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0608))
#define OS_SRC_CAN2INT3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x060C))
#define OS_SRC_CAN2INT4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0610))
#define OS_SRC_CAN2INT5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0614))
#define OS_SRC_CAN2INT6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0618))
#define OS_SRC_CAN2INT7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x061C))
#define OS_SRC_CAN2INT8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0620))
#define OS_SRC_CAN2INT9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0624))
#define OS_SRC_CAN2INT10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0628))
#define OS_SRC_CAN2INT11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x062C))
#define OS_SRC_CAN2INT12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0630))
#define OS_SRC_CAN2INT13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0634))
#define OS_SRC_CAN2INT14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0638))
#define OS_SRC_CAN2INT15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x063C))
#define OS_SRC_VADCG0SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0670))
#define OS_SRC_VADCG0SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0674))
#define OS_SRC_VADCG0SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0678))
#define OS_SRC_VADCG0SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x067C))
#define OS_SRC_VADCG1SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0680))
#define OS_SRC_VADCG1SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0684))
#define OS_SRC_VADCG1SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0688))
#define OS_SRC_VADCG1SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x068C))
#define OS_SRC_VADCG2SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0690))
#define OS_SRC_VADCG2SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0694))
#define OS_SRC_VADCG2SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0698))
#define OS_SRC_VADCG2SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x069C))
#define OS_SRC_VADCG3SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06A0))
#define OS_SRC_VADCG3SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06A4))
#define OS_SRC_VADCG3SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06A8))
#define OS_SRC_VADCG3SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06AC))
#define OS_SRC_VADCG4SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06B0))
#define OS_SRC_VADCG4SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06B4))
#define OS_SRC_VADCG4SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06B8))
#define OS_SRC_VADCG4SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06BC))
#define OS_SRC_VADCG5SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06C0))
#define OS_SRC_VADCG5SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06C4))
#define OS_SRC_VADCG5SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06C8))
#define OS_SRC_VADCG5SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06CC))
#define OS_SRC_VADCG6SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06D0))
#define OS_SRC_VADCG6SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06D4))
#define OS_SRC_VADCG6SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06D8))
#define OS_SRC_VADCG6SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06DC))
#define OS_SRC_VADCG7SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06E0))
#define OS_SRC_VADCG7SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06E4))
#define OS_SRC_VADCG7SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06E8))
#define OS_SRC_VADCG7SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06EC))
#define OS_SRC_VADCG8SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06F0))
#define OS_SRC_VADCG8SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06F4))
#define OS_SRC_VADCG8SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06F8))
#define OS_SRC_VADCG8SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x06FC))
#define OS_SRC_VADCG9SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0700))
#define OS_SRC_VADCG9SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0704))
#define OS_SRC_VADCG9SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0708))
#define OS_SRC_VADCG9SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x070C))
#define OS_SRC_VADCG10SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0710))
#define OS_SRC_VADCG10SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0714))
#define OS_SRC_VADCG10SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0718))
#define OS_SRC_VADCG10SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x071C))
#define OS_SRC_VADCG11SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0720))
#define OS_SRC_VADCG11SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0724))
#define OS_SRC_VADCG11SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0728))
#define OS_SRC_VADCG11SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x072C))
#define OS_SRC_VADCG12SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0730))
#define OS_SRC_VADCG13SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0734))
#define OS_SRC_VADCG14SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0738))
#define OS_SRC_VADCG15SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x073C))
#define OS_SRC_VADCG16SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0740))
#define OS_SRC_VADCG17SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0744))
#define OS_SRC_VADCG18SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0748))
#define OS_SRC_VADCG19SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x074C))
#define OS_SRC_VADCCG0SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0750))
#define OS_SRC_VADCCG0SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0754))
#define OS_SRC_VADCCG0SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0758))
#define OS_SRC_VADCCG0SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x075C))
#define OS_SRC_VADCCG1SR0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0760))
#define OS_SRC_VADCCG1SR1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0764))
#define OS_SRC_VADCCG1SR2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0768))
#define OS_SRC_VADCCG1SR3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x076C))
#define OS_SRC_DSADCSRM0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0770))
#define OS_SRC_DSADCSRM1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0778))
#define OS_SRC_DSADCSRM2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0780))
#define OS_SRC_DSADCSRM3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0788))
#define OS_SRC_DSADCSRM4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0790))
#define OS_SRC_DSADCSRM5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0798))
#define OS_SRC_DSADCSRM6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07A0))
#define OS_SRC_DSADCSRM7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07A8))
#define OS_SRC_DSADCSRM8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07B0))
#define OS_SRC_DSADCSRM9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07B8))
#define OS_SRC_DSADCSRM10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07C0))
#define OS_SRC_DSADCSRM11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07C8))
#define OS_SRC_DSADCSRM12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07D0))
#define OS_SRC_DSADCSRM13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07D8))
#define OS_SRC_DSADCSRA0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0774))
#define OS_SRC_DSADCSRA1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x077C))
#define OS_SRC_DSADCSRA2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0784))
#define OS_SRC_DSADCSRA3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x078C))
#define OS_SRC_DSADCSRA4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0794))
#define OS_SRC_DSADCSRA5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x079C))
#define OS_SRC_DSADCSRA6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07A4))
#define OS_SRC_DSADCSRA7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07AC))
#define OS_SRC_DSADCSRA8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07B4))
#define OS_SRC_DSADCSRA9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07BC))
#define OS_SRC_DSADCSRA10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07C4))
#define OS_SRC_DSADCSRA11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07CC))
#define OS_SRC_DSADCSRA12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07D4))
#define OS_SRC_DSADCSRA13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x07DC))
#define OS_SRC_ERAY0INT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0800))
#define OS_SRC_ERAY0INT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0804))
#define OS_SRC_ERAY0TINT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0808))
#define OS_SRC_ERAY0TINT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x080C))
#define OS_SRC_ERAY0NDAT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0810))
#define OS_SRC_ERAY0NDAT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0814))
#define OS_SRC_ERAY0MBSC0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0818))
#define OS_SRC_ERAY0MBSC1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x081C))
#define OS_SRC_ERAY0OBUSY (*(os_tricoresrn_t *)(OS_SRCBASE+0x0820))
#define OS_SRC_ERAY0IBUSY (*(os_tricoresrn_t *)(OS_SRCBASE+0x0824))
#define OS_SRC_ERAY1INT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0830))
#define OS_SRC_ERAY1INT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0834))
#define OS_SRC_ERAY1TINT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0838))
#define OS_SRC_ERAY1TINT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x083C))
#define OS_SRC_ERAY1NDAT0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0840))
#define OS_SRC_ERAY1NDAT1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0844))
#define OS_SRC_ERAY1MBSC0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0848))
#define OS_SRC_ERAY1MBSC1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x084C))
#define OS_SRC_ERAY1OBUSY (*(os_tricoresrn_t *)(OS_SRCBASE+0x0850))
#define OS_SRC_ERAY1IBUSY (*(os_tricoresrn_t *)(OS_SRCBASE+0x0854))
#define OS_SRC_PMUHOST (*(os_tricoresrn_t *)(OS_SRCBASE+0x0860))
#define OS_SRC_PMUFSI (*(os_tricoresrn_t *)(OS_SRCBASE+0x0864))
#define OS_SRC_HSM0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0870))
#define OS_SRC_HSM1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0874))
#define OS_SRC_SCUERU0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0880))
#define OS_SRC_SCUERU1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0884))
#define OS_SRC_SCUERU2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0888))
#define OS_SRC_SCUERU3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x088C))
#define OS_SRC_PMSDTS (*(os_tricoresrn_t *)(OS_SRCBASE+0x089C))
#define OS_SRC_PMS0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08A0))
#define OS_SRC_PMS1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08A4))
#define OS_SRC_PMS2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08A8))
#define OS_SRC_PMS3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08AC))
#define OS_SRC_SCR (*(os_tricoresrn_t *)(OS_SRCBASE+0x08B0))
#define OS_SRC_SMU0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08C0))
#define OS_SRC_SMU1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08C4))
#define OS_SRC_SMU2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08C8))
#define OS_SRC_PSI50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08D0))
#define OS_SRC_PSI51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08D4))
#define OS_SRC_PSI52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08D8))
#define OS_SRC_PSI53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08DC))
#define OS_SRC_PSI54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08E0))
#define OS_SRC_PSI55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08E4))
#define OS_SRC_PSI56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08E8))
#define OS_SRC_PSI57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x08EC))
#define OS_SRC_DAM0LI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0900))
#define OS_SRC_DAM1LI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0918))
#define OS_SRC_DAM0RI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0904))
#define OS_SRC_DAM1RI0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x091C))
#define OS_SRC_DAM0LI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0908))
#define OS_SRC_DAM1LI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0920))
#define OS_SRC_DAM0RI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x090C))
#define OS_SRC_DAM1RI1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0924))
#define OS_SRC_DAM0DR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0910))
#define OS_SRC_DAM1DR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0928))
#define OS_SRC_DAM0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0914))
#define OS_SRC_DAM1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x092C))
#define OS_SRC_CIFMI (*(os_tricoresrn_t *)(OS_SRCBASE+0x0930))
#define OS_SRC_CIFMIEP (*(os_tricoresrn_t *)(OS_SRCBASE+0x0934))
#define OS_SRC_CIFISP (*(os_tricoresrn_t *)(OS_SRCBASE+0x0938))
#define OS_SRC_CIFMJPEG (*(os_tricoresrn_t *)(OS_SRCBASE+0x093C))
#define OS_SRC_PSI5S0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0950))
#define OS_SRC_PSI5S1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0954))
#define OS_SRC_PSI5S2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0958))
#define OS_SRC_PSI5S3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x095C))
#define OS_SRC_PSI5S4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0960))
#define OS_SRC_PSI5S5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0964))
#define OS_SRC_PSI5S6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0968))
#define OS_SRC_PSI5S7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x096C))
#define OS_SRC_RIF0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0970))
#define OS_SRC_RIF0INT (*(os_tricoresrn_t *)(OS_SRCBASE+0x0974))
#define OS_SRC_RIF1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0978))
#define OS_SRC_RIF1INT (*(os_tricoresrn_t *)(OS_SRCBASE+0x097C))
#define OS_SRC_SPU0ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0980))
#define OS_SRC_SPU0INT (*(os_tricoresrn_t *)(OS_SRCBASE+0x0984))
#define OS_SRC_SPU1ERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0988))
#define OS_SRC_SPU1INT (*(os_tricoresrn_t *)(OS_SRCBASE+0x098C))
#define OS_SRC_GPSR00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0990))
#define OS_SRC_GPSR01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0994))
#define OS_SRC_GPSR02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0998))
#define OS_SRC_GPSR03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x099C))
#define OS_SRC_GPSR04 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09A0))
#define OS_SRC_GPSR05 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09A4))
#define OS_SRC_GPSR06 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09A8))
#define OS_SRC_GPSR07 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09AC))
#define OS_SRC_GPSR10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09B0))
#define OS_SRC_GPSR11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09B4))
#define OS_SRC_GPSR12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09B8))
#define OS_SRC_GPSR13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09BC))
#define OS_SRC_GPSR14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09C0))
#define OS_SRC_GPSR15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09C4))
#define OS_SRC_GPSR16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09C8))
#define OS_SRC_GPSR17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09CC))
#define OS_SRC_GPSR20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09D0))
#define OS_SRC_GPSR21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09D4))
#define OS_SRC_GPSR22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09D8))
#define OS_SRC_GPSR23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09DC))
#define OS_SRC_GPSR24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09E0))
#define OS_SRC_GPSR25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09E4))
#define OS_SRC_GPSR26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09E8))
#define OS_SRC_GPSR27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09EC))
#define OS_SRC_GPSR30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09F0))
#define OS_SRC_GPSR31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09F4))
#define OS_SRC_GPSR32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09F8))
#define OS_SRC_GPSR33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x09FC))
#define OS_SRC_GPSR34 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A00))
#define OS_SRC_GPSR35 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A04))
#define OS_SRC_GPSR36 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A08))
#define OS_SRC_GPSR37 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A0C))
#define OS_SRC_GPSR40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A10))
#define OS_SRC_GPSR41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A14))
#define OS_SRC_GPSR42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A18))
#define OS_SRC_GPSR43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A1C))
#define OS_SRC_GPSR44 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A20))
#define OS_SRC_GPSR45 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A24))
#define OS_SRC_GPSR46 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A28))
#define OS_SRC_GPSR47 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A2C))
#define OS_SRC_GPSR50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A30))
#define OS_SRC_GPSR51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A34))
#define OS_SRC_GPSR52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A38))
#define OS_SRC_GPSR53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A3C))
#define OS_SRC_GPSR54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A40))
#define OS_SRC_GPSR55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A44))
#define OS_SRC_GPSR56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A48))
#define OS_SRC_GPSR57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A4C))
#define OS_SRC_GTMAEIIRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A70))
#define OS_SRC_GTMARUIRQ0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A74))
#define OS_SRC_GTMARUIRQ1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A78))
#define OS_SRC_GTMARUIRQ2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A7C))
#define OS_SRC_GTMBRCIRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A80))
#define OS_SRC_GTMCMPIRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A84))
#define OS_SRC_GTMSPE0IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A88))
#define OS_SRC_GTMSPE1IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A8C))
#define OS_SRC_GTMSPE2IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A90))
#define OS_SRC_GTMSPE3IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A94))
#define OS_SRC_GTMSPE4IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A98))
#define OS_SRC_GTMSPE5IRQ (*(os_tricoresrn_t *)(OS_SRCBASE+0x0A9C))
#define OS_SRC_GTMPSM00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AA0))
#define OS_SRC_GTMPSM01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AA4))
#define OS_SRC_GTMPSM02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AA8))
#define OS_SRC_GTMPSM03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AAC))
#define OS_SRC_GTMPSM04 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AB0))
#define OS_SRC_GTMPSM05 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AB4))
#define OS_SRC_GTMPSM06 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AB8))
#define OS_SRC_GTMPSM07 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0ABC))
#define OS_SRC_GTMPSM10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AC0))
#define OS_SRC_GTMPSM11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AC4))
#define OS_SRC_GTMPSM12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AC8))
#define OS_SRC_GTMPSM13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0ACC))
#define OS_SRC_GTMPSM14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AD0))
#define OS_SRC_GTMPSM15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AD4))
#define OS_SRC_GTMPSM16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AD8))
#define OS_SRC_GTMPSM17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0ADC))
#define OS_SRC_GTMPSM20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AE0))
#define OS_SRC_GTMPSM21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AE4))
#define OS_SRC_GTMPSM22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AE8))
#define OS_SRC_GTMPSM23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AEC))
#define OS_SRC_GTMPSM24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AF0))
#define OS_SRC_GTMPSM25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AF4))
#define OS_SRC_GTMPSM26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AF8))
#define OS_SRC_GTMPSM27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0AFC))
#define OS_SRC_GTMDPLL0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B00))
#define OS_SRC_GTMDPLL1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B04))
#define OS_SRC_GTMDPLL2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B08))
#define OS_SRC_GTMDPLL3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B0C))
#define OS_SRC_GTMDPLL4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B10))
#define OS_SRC_GTMDPLL5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B14))
#define OS_SRC_GTMDPLL6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B18))
#define OS_SRC_GTMDPLL7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B1C))
#define OS_SRC_GTMDPLL8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B20))
#define OS_SRC_GTMDPLL9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B24))
#define OS_SRC_GTMDPLL10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B28))
#define OS_SRC_GTMDPLL11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B2C))
#define OS_SRC_GTMDPLL12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B30))
#define OS_SRC_GTMDPLL13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B34))
#define OS_SRC_GTMDPLL14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B38))
#define OS_SRC_GTMDPLL15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B3C))
#define OS_SRC_GTMDPLL16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B40))
#define OS_SRC_GTMDPLL17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B44))
#define OS_SRC_GTMDPLL18 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B48))
#define OS_SRC_GTMDPLL19 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B4C))
#define OS_SRC_GTMDPLL20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B50))
#define OS_SRC_GTMDPLL21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B54))
#define OS_SRC_GTMDPLL22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B58))
#define OS_SRC_GTMDPLL23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B5C))
#define OS_SRC_GTMDPLL24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B60))
#define OS_SRC_GTMDPLL25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B64))
#define OS_SRC_GTMDPLL26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B68))
#define OS_SRC_GTMERR (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B70))
#define OS_SRC_GTMTIM00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B90))
#define OS_SRC_GTMTIM01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B94))
#define OS_SRC_GTMTIM02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B98))
#define OS_SRC_GTMTIM03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0B9C))
#define OS_SRC_GTMTIM04 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BA0))
#define OS_SRC_GTMTIM05 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BA4))
#define OS_SRC_GTMTIM06 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BA8))
#define OS_SRC_GTMTIM07 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BAC))
#define OS_SRC_GTMTIM10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BB0))
#define OS_SRC_GTMTIM11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BB4))
#define OS_SRC_GTMTIM12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BB8))
#define OS_SRC_GTMTIM13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BBC))
#define OS_SRC_GTMTIM14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BC0))
#define OS_SRC_GTMTIM15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BC4))
#define OS_SRC_GTMTIM16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BC8))
#define OS_SRC_GTMTIM17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BCC))
#define OS_SRC_GTMTIM20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BD0))
#define OS_SRC_GTMTIM21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BD4))
#define OS_SRC_GTMTIM22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BD8))
#define OS_SRC_GTMTIM23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BDC))
#define OS_SRC_GTMTIM24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BE0))
#define OS_SRC_GTMTIM25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BE4))
#define OS_SRC_GTMTIM26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BE8))
#define OS_SRC_GTMTIM27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BEC))
#define OS_SRC_GTMTIM30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BF0))
#define OS_SRC_GTMTIM31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BF4))
#define OS_SRC_GTMTIM32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BF8))
#define OS_SRC_GTMTIM33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0BFC))
#define OS_SRC_GTMTIM34 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C00))
#define OS_SRC_GTMTIM35 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C04))
#define OS_SRC_GTMTIM36 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C08))
#define OS_SRC_GTMTIM37 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C0C))
#define OS_SRC_GTMTIM40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C10))
#define OS_SRC_GTMTIM41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C14))
#define OS_SRC_GTMTIM42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C18))
#define OS_SRC_GTMTIM43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C1C))
#define OS_SRC_GTMTIM44 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C20))
#define OS_SRC_GTMTIM45 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C24))
#define OS_SRC_GTMTIM46 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C28))
#define OS_SRC_GTMTIM47 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C2C))
#define OS_SRC_GTMTIM50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C30))
#define OS_SRC_GTMTIM51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C34))
#define OS_SRC_GTMTIM52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C38))
#define OS_SRC_GTMTIM53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C3C))
#define OS_SRC_GTMTIM54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C40))
#define OS_SRC_GTMTIM55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C44))
#define OS_SRC_GTMTIM56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C48))
#define OS_SRC_GTMTIM57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C4C))
#define OS_SRC_GTMTIM60 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C50))
#define OS_SRC_GTMTIM61 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C54))
#define OS_SRC_GTMTIM62 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C58))
#define OS_SRC_GTMTIM63 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C5C))
#define OS_SRC_GTMTIM64 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C60))
#define OS_SRC_GTMTIM65 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C64))
#define OS_SRC_GTMTIM66 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C68))
#define OS_SRC_GTMTIM67 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C6C))
#define OS_SRC_GTMTIM70 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C70))
#define OS_SRC_GTMTIM71 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C74))
#define OS_SRC_GTMTIM72 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C78))
#define OS_SRC_GTMTIM73 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C7C))
#define OS_SRC_GTMTIM74 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C80))
#define OS_SRC_GTMTIM75 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C84))
#define OS_SRC_GTMTIM76 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C88))
#define OS_SRC_GTMTIM77 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0C8C))
#define OS_SRC_GTMMCS00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CB0))
#define OS_SRC_GTMMCS01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CB4))
#define OS_SRC_GTMMCS02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CB8))
#define OS_SRC_GTMMCS03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CBC))
#define OS_SRC_GTMMCS04 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CC0))
#define OS_SRC_GTMMCS05 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CC4))
#define OS_SRC_GTMMCS06 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CC8))
#define OS_SRC_GTMMCS07 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CCC))
#define OS_SRC_GTMMCS10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CD0))
#define OS_SRC_GTMMCS11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CD4))
#define OS_SRC_GTMMCS12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CD8))
#define OS_SRC_GTMMCS13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CDC))
#define OS_SRC_GTMMCS14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CE0))
#define OS_SRC_GTMMCS15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CE4))
#define OS_SRC_GTMMCS16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CE8))
#define OS_SRC_GTMMCS17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CEC))
#define OS_SRC_GTMMCS20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CF0))
#define OS_SRC_GTMMCS21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CF4))
#define OS_SRC_GTMMCS22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CF8))
#define OS_SRC_GTMMCS23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0CFC))
#define OS_SRC_GTMMCS24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D00))
#define OS_SRC_GTMMCS25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D04))
#define OS_SRC_GTMMCS26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D08))
#define OS_SRC_GTMMCS27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D0C))
#define OS_SRC_GTMMCS30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D10))
#define OS_SRC_GTMMCS31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D14))
#define OS_SRC_GTMMCS32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D18))
#define OS_SRC_GTMMCS33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D1C))
#define OS_SRC_GTMMCS34 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D20))
#define OS_SRC_GTMMCS35 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D24))
#define OS_SRC_GTMMCS36 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D28))
#define OS_SRC_GTMMCS37 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D2C))
#define OS_SRC_GTMMCS40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D30))
#define OS_SRC_GTMMCS41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D34))
#define OS_SRC_GTMMCS42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D38))
#define OS_SRC_GTMMCS43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D3C))
#define OS_SRC_GTMMCS44 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D40))
#define OS_SRC_GTMMCS45 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D44))
#define OS_SRC_GTMMCS46 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D48))
#define OS_SRC_GTMMCS47 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D4C))
#define OS_SRC_GTMMCS50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D50))
#define OS_SRC_GTMMCS51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D54))
#define OS_SRC_GTMMCS52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D58))
#define OS_SRC_GTMMCS53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D5C))
#define OS_SRC_GTMMCS54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D60))
#define OS_SRC_GTMMCS55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D64))
#define OS_SRC_GTMMCS56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D68))
#define OS_SRC_GTMMCS57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D6C))
#define OS_SRC_GTMMCS60 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D70))
#define OS_SRC_GTMMCS61 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D74))
#define OS_SRC_GTMMCS62 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D78))
#define OS_SRC_GTMMCS63 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D7C))
#define OS_SRC_GTMMCS64 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D80))
#define OS_SRC_GTMMCS65 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D84))
#define OS_SRC_GTMMCS66 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D88))
#define OS_SRC_GTMMCS67 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D8C))
#define OS_SRC_GTMMCS70 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D90))
#define OS_SRC_GTMMCS71 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D94))
#define OS_SRC_GTMMCS72 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D98))
#define OS_SRC_GTMMCS73 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0D9C))
#define OS_SRC_GTMMCS74 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DA0))
#define OS_SRC_GTMMCS75 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DA4))
#define OS_SRC_GTMMCS76 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DA8))
#define OS_SRC_GTMMCS77 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DAC))
#define OS_SRC_GTMMCS80 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DB0))
#define OS_SRC_GTMMCS81 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DB4))
#define OS_SRC_GTMMCS82 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DB8))
#define OS_SRC_GTMMCS83 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DBC))
#define OS_SRC_GTMMCS84 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DC0))
#define OS_SRC_GTMMCS85 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DC4))
#define OS_SRC_GTMMCS86 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DC8))
#define OS_SRC_GTMMCS87 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DCC))
#define OS_SRC_GTMMCS90 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DD0))
#define OS_SRC_GTMMCS91 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DD4))
#define OS_SRC_GTMMCS92 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DD8))
#define OS_SRC_GTMMCS93 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DDC))
#define OS_SRC_GTMMCS94 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DE0))
#define OS_SRC_GTMMCS95 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DE4))
#define OS_SRC_GTMMCS96 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DE8))
#define OS_SRC_GTMMCS97 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0DEC))
#define OS_SRC_GTMTOM00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E10))
#define OS_SRC_GTMTOM01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E14))
#define OS_SRC_GTMTOM02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E18))
#define OS_SRC_GTMTOM03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E1C))
#define OS_SRC_GTMTOM04 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E20))
#define OS_SRC_GTMTOM05 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E24))
#define OS_SRC_GTMTOM06 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E28))
#define OS_SRC_GTMTOM07 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E2C))
#define OS_SRC_GTMTOM10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E30))
#define OS_SRC_GTMTOM11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E34))
#define OS_SRC_GTMTOM12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E38))
#define OS_SRC_GTMTOM13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E3C))
#define OS_SRC_GTMTOM14 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E40))
#define OS_SRC_GTMTOM15 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E44))
#define OS_SRC_GTMTOM16 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E48))
#define OS_SRC_GTMTOM17 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E4C))
#define OS_SRC_GTMTOM20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E50))
#define OS_SRC_GTMTOM21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E54))
#define OS_SRC_GTMTOM22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E58))
#define OS_SRC_GTMTOM23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E5C))
#define OS_SRC_GTMTOM24 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E60))
#define OS_SRC_GTMTOM25 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E64))
#define OS_SRC_GTMTOM26 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E68))
#define OS_SRC_GTMTOM27 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E6C))
#define OS_SRC_GTMTOM30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E70))
#define OS_SRC_GTMTOM31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E74))
#define OS_SRC_GTMTOM32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E78))
#define OS_SRC_GTMTOM33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E7C))
#define OS_SRC_GTMTOM34 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E80))
#define OS_SRC_GTMTOM35 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E84))
#define OS_SRC_GTMTOM36 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E88))
#define OS_SRC_GTMTOM37 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E8C))
#define OS_SRC_GTMTOM40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E90))
#define OS_SRC_GTMTOM41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E94))
#define OS_SRC_GTMTOM42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E98))
#define OS_SRC_GTMTOM43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0E9C))
#define OS_SRC_GTMTOM44 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EA0))
#define OS_SRC_GTMTOM45 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EA4))
#define OS_SRC_GTMTOM46 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EA8))
#define OS_SRC_GTMTOM47 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EAC))
#define OS_SRC_GTMTOM50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EB0))
#define OS_SRC_GTMTOM51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EB4))
#define OS_SRC_GTMTOM52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EB8))
#define OS_SRC_GTMTOM53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EBC))
#define OS_SRC_GTMTOM54 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EC0))
#define OS_SRC_GTMTOM55 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EC4))
#define OS_SRC_GTMTOM56 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EC8))
#define OS_SRC_GTMTOM57 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0ECC))
#define OS_SRC_GTMATOM00 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EF0))
#define OS_SRC_GTMATOM01 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EF4))
#define OS_SRC_GTMATOM02 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EF8))
#define OS_SRC_GTMATOM03 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0EFC))
#define OS_SRC_GTMATOM10 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F00))
#define OS_SRC_GTMATOM11 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F04))
#define OS_SRC_GTMATOM12 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F08))
#define OS_SRC_GTMATOM13 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F0C))
#define OS_SRC_GTMATOM20 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F10))
#define OS_SRC_GTMATOM21 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F14))
#define OS_SRC_GTMATOM22 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F18))
#define OS_SRC_GTMATOM23 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F1C))
#define OS_SRC_GTMATOM30 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F20))
#define OS_SRC_GTMATOM31 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F24))
#define OS_SRC_GTMATOM32 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F28))
#define OS_SRC_GTMATOM33 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F2C))
#define OS_SRC_GTMATOM40 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F30))
#define OS_SRC_GTMATOM41 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F34))
#define OS_SRC_GTMATOM42 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F38))
#define OS_SRC_GTMATOM43 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F3C))
#define OS_SRC_GTMATOM50 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F40))
#define OS_SRC_GTMATOM51 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F44))
#define OS_SRC_GTMATOM52 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F48))
#define OS_SRC_GTMATOM53 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F4C))
#define OS_SRC_GTMATOM60 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F50))
#define OS_SRC_GTMATOM61 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F54))
#define OS_SRC_GTMATOM62 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F58))
#define OS_SRC_GTMATOM63 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F5C))
#define OS_SRC_GTMATOM70 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F60))
#define OS_SRC_GTMATOM71 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F64))
#define OS_SRC_GTMATOM72 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F68))
#define OS_SRC_GTMATOM73 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F6C))
#define OS_SRC_GTMATOM80 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F70))
#define OS_SRC_GTMATOM81 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F74))
#define OS_SRC_GTMATOM82 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F78))
#define OS_SRC_GTMATOM83 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F7C))
#define OS_SRC_GTMATOM90 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F80))
#define OS_SRC_GTMATOM91 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F84))
#define OS_SRC_GTMATOM92 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F88))
#define OS_SRC_GTMATOM93 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F8C))
#define OS_SRC_GTMATOM100 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F90))
#define OS_SRC_GTMATOM101 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F94))
#define OS_SRC_GTMATOM102 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F98))
#define OS_SRC_GTMATOM103 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0F9C))
#define OS_SRC_GTMATOM110 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FA0))
#define OS_SRC_GTMATOM111 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FA4))
#define OS_SRC_GTMATOM112 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FA8))
#define OS_SRC_GTMATOM113 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FAC))
#define OS_SRC_GTMMCSW0 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FD0))
#define OS_SRC_GTMMCSW1 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FD4))
#define OS_SRC_GTMMCSW2 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FD8))
#define OS_SRC_GTMMCSW3 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FDC))
#define OS_SRC_GTMMCSW4 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FE0))
#define OS_SRC_GTMMCSW5 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FE4))
#define OS_SRC_GTMMCSW6 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FE8))
#define OS_SRC_GTMMCSW7 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FEC))
#define OS_SRC_GTMMCSW8 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FF0))
#define OS_SRC_GTMMCSW9 (*(os_tricoresrn_t *)(OS_SRCBASE+0x0FF4))


/* Peripheral modules that are of interest to the OS
 *
 * The STM is the system timer module and contains the 64-bit free-running counter used for all time measurements.
 * On the TC39XX we have 6 STM modules and 2 possible interrupts per module.
 *
 * CHECK: RULE 402 OFF	(OS_pwr isn't a constant-like macro; it's a variable-like macros)
*/
#define OS_PWR_BASE		OS_U(0xf0036000)
#include <TRICORE/Os_TRICORE_pwr.h>
#define OS_pwr			(*(os_tricorepwr_t *)OS_PWR_BASE)

/* These are the system timer's (STM[0-5]) base addresses. */
#define OS_N_STM		6
#define OS_STM0_BASE	OS_U(0xf0001000)
#define OS_STM1_BASE	OS_U(0xf0001100)
#define OS_STM2_BASE	OS_U(0xf0001200)
#define OS_STM3_BASE	OS_U(0xf0001300)
#define OS_STM4_BASE	OS_U(0xf0001400)
#define OS_STM5_BASE	OS_U(0xf0001500)

/* STM0 is the default system timer. */
#define OS_STM_BASE OS_STM0_BASE

#define OS_STM_HAS_COMPARE	1

/* OCDS Control and Status Register (OCS) */
#define OS_STM_OCS_OFFSET	0xe8
#define OS_STM0_OCS			(*(os_reg32_t *)(OS_STM0_BASE+OS_STM_OCS_OFFSET))
#define OS_STM1_OCS			(*(os_reg32_t *)(OS_STM1_BASE+OS_STM_OCS_OFFSET))
#define OS_STM2_OCS			(*(os_reg32_t *)(OS_STM2_BASE+OS_STM_OCS_OFFSET))
#define OS_STM3_OCS			(*(os_reg32_t *)(OS_STM3_BASE+OS_STM_OCS_OFFSET))
#define OS_STM4_OCS			(*(os_reg32_t *)(OS_STM4_BASE+OS_STM_OCS_OFFSET))
#define OS_STM5_OCS			(*(os_reg32_t *)(OS_STM5_BASE+OS_STM_OCS_OFFSET))

#endif
/* Editor settings; DO NOT DELETE
 * vi:set ts=4:
*/
