#ifndef __Idiab_tcasm
#define __Idiab_tcasm
/*	Copyright (c) 2011 Wind River Systems, Inc.				*/
/*	All Rights Reserved							*/
/*	Implementation module : tcasm.h						*/
/*										*/
/*	Description :								*/
/*	This module provides access to the target assembly instructions		*/
/*	through intrinsic function prototypes.					*/


#ifndef	SUPPRESS_INTRINSIC_FUNCTIONS

extern void __memory_barrier( void) __attribute__((intrinsic_function(0x103, 4, "diabmbar") ));
extern void __scheduling_barrier( void) __attribute__((intrinsic_function(9, 4, "$$sb") ));
extern int _abs( int) __attribute__((intrinsic_pseudo(1, "abs") ));
extern int _absb( int) __attribute__((intrinsic_function(0x10a, 1, "abs.b") ));
extern int _absdif( int,  int) __attribute__((intrinsic_function(0x10b, 1, "absdif") ));
extern int _absdifb( int,  int) __attribute__((intrinsic_function(0x10b, 1, "absdif.b") ));
extern int _absdifh( int,  int) __attribute__((intrinsic_function(0x10b, 1, "absdif.h") ));
extern int _absdifs( int,  int) __attribute__((intrinsic_function(0x10b, 1, "absdifs") ));
extern int _absdifsh( int,  int) __attribute__((intrinsic_function(0x10b, 1, "absdifs.h") ));
extern int _absh( int) __attribute__((intrinsic_function(0x10a, 1, "abs.h") ));
extern int _abss( int) __attribute__((intrinsic_function(0x10a, 1, "abss") ));
extern int _abssh( int) __attribute__((intrinsic_function(0x10a, 1, "abss.h") ));
extern unsigned _addb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "add.b") ));
extern int _addc( int,  int) __attribute__((intrinsic_function(0x10b, 2, "addc") ));
extern float _addf( float,  float) __attribute__((intrinsic_function(0x10b, 0, "add.f") ));
extern unsigned _addh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "add.h") ));
extern int _addi( int,  const unsigned int) __attribute__((intrinsic_function(0x10d, 2, "addi") ));
extern int _addih( int,  const unsigned int) __attribute__((intrinsic_function(0x10d, 0, "addih") ));
extern void* _addiha( void*,  const unsigned int) __attribute__((intrinsic_function(0x10e, 0, "addih.a") ));
extern int _adds( int,  int) __attribute__((intrinsic_function(0x10b, 1, "adds") ));
extern void* _addsca( void*,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x10f, 0, "addsc.a") ));
extern unsigned _addsh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "adds.h") ));
extern unsigned _addshu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "adds.hu") ));
extern unsigned _addsu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 1, "adds.u") ));
extern int _addx( int,  int) __attribute__((intrinsic_function(0x10b, 2, "addx") ));
extern unsigned _and( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "and") ));
extern unsigned _andandnt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "and.andn.t") ));
extern unsigned _andandt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "and.and.t") ));
extern unsigned _andeq( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "and.eq") ));
extern unsigned _andge( int,  int) __attribute__((intrinsic_function(0x10b, 0, "and.ge") ));
extern unsigned _andgeu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "and.ge.u") ));
extern unsigned _andlt( int,  int) __attribute__((intrinsic_function(0x10b, 0, "and.lt") ));
extern unsigned _andltu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "and.lt.u") ));
extern unsigned _andn( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "andn") ));
extern unsigned _andne( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "and.ne") ));
extern unsigned _andnort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "and.nor.t") ));
extern unsigned _andnt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "andn.t") ));
extern unsigned _andort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "and.or.t") ));
extern unsigned _andt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "and.t") ));
extern void _bisr( const unsigned int) __attribute__((intrinsic_function(0x100, 0, "bisr") ));
extern int _bmerge( int,  int) __attribute__((intrinsic_pseudo(1, "bmerge") ));
extern unsigned long long _bsplit( unsigned) __attribute__((intrinsic_function(0x133, 0, "bsplit") ));
extern void _cacheai( void*) __attribute__((intrinsic_function(0x110, 0, "cachea.i") ));
extern void _cacheaw( void*) __attribute__((intrinsic_function(0x110, 0, "cachea.w") ));
extern void _cacheawi( void*) __attribute__((intrinsic_function(0x110, 0, "cachea.wi") ));
extern void _cacheii( void*) __attribute__((intrinsic_function(0x107, 0, "cachei.i") ));
extern void _cacheiw( void*) __attribute__((intrinsic_function(0x107, 0, "cachei.w") ));
extern void _cacheiwi( void*) __attribute__((intrinsic_function(0x107, 0, "cachei.wi") ));
extern int _cadd( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "cadd") ));
extern int _caddn( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "caddn") ));
extern int _clo( int) __attribute__((intrinsic_pseudo(1, "clo") ));
extern unsigned _cloh( unsigned) __attribute__((intrinsic_function(0x105, 0, "clo.h") ));
extern int _cls( int) __attribute__((intrinsic_pseudo(1, "cls") ));
extern unsigned _clsh( unsigned) __attribute__((intrinsic_function(0x105, 0, "cls.h") ));
extern int _clz( int) __attribute__((intrinsic_pseudo(1, "clz") ));
extern unsigned _clzh( unsigned) __attribute__((intrinsic_function(0x105, 0, "clz.h") ));
extern int _cmov( int,  int) __attribute__((intrinsic_function(0x111, 0, "cmov") ));
extern int _cmovn( int,  int) __attribute__((intrinsic_function(0x111, 0, "cmovn") ));
extern unsigned _cmpf( float,  float) __attribute__((intrinsic_function(0x10b, 0, "cmp.f") ));
extern unsigned _cmpswapw( void*,  const unsigned int,  unsigned long long) __attribute__((intrinsic_function(0x160, 0, "cmpswap.w") ));
extern int _crc32( int,  int) __attribute__((intrinsic_pseudo(1, "crc32") ));
extern unsigned _crc32_b( unsigned,  unsigned) __attribute__((intrinsic_pseudo(1, "crc32.b") ));
extern unsigned _crc32b_w( unsigned,  unsigned) __attribute__((intrinsic_pseudo(1, "crc32b.w") ));
extern unsigned _crc32l_w( unsigned,  unsigned) __attribute__((intrinsic_pseudo(1, "crc32l.w") ));
extern int _crcn( int,  int,  int) __attribute__((intrinsic_function(0x112, 1, "crcn") ));
extern int _csub( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "csub") ));
extern int _csubn( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "csubn") ));
extern void _debug( void) __attribute__((intrinsic_function(0x103, 0, "debug") ));
extern unsigned _dextr( unsigned,  unsigned,  unsigned) __attribute__((intrinsic_function(0x112, 0, "dextr") ));
extern void _disable( void) __attribute__((intrinsic_function(0x103, 0, "disable") ));
extern unsigned _disable__d( void) __attribute__((intrinsic_function(0x16f, 0, "disable") ));
extern long long _div( int,  int) __attribute__((intrinsic_function(0x134, 0, "div") ));
extern float _divf( float,  float) __attribute__((intrinsic_function(0x10b, 0, "div.f") ));
extern unsigned long long _divu( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "div.u") ));
extern void _dsync( void) __attribute__((intrinsic_function(0x103, 4, "dsync") ));
extern unsigned long long _dvadj( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x135, 0, "dvadj") ));
extern unsigned long long _dvinit( int,  int) __attribute__((intrinsic_function(0x134, 0, "dvinit") ));
extern unsigned long long _dvinitb( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "dvinit.b") ));
extern unsigned long long _dvinitbu( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "dvinit.bu") ));
extern unsigned long long _dvinith( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "dvinit.h") ));
extern unsigned long long _dvinithu( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "dvinit.hu") ));
extern unsigned long long _dvinitu( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 0, "dvinit.u") ));
extern unsigned long long _dvstep( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "dvstep") ));
extern unsigned long long _dvstepu( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "dvstep.u") ));
extern void _enable( void) __attribute__((intrinsic_function(0x103, 0, "enable") ));
extern unsigned _eq( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "eq") ));
extern unsigned _eqa( unsigned*,  unsigned*) __attribute__((intrinsic_function(0x113, 2, "eq.a") ));
extern unsigned _eqanyb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "eqany.b") ));
extern unsigned _eqanyh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "eqany.h") ));
extern unsigned _eqb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "eq.b") ));
extern unsigned _eqh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "eq.h") ));
extern unsigned _eqw( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "eq.w") ));
extern unsigned _eqza( unsigned*) __attribute__((intrinsic_function(0x114, 0, "eqz.a") ));
extern int _extr( int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x108, 0, "extr") ));
extern unsigned _extru( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x108, 0, "extr.u") ));
extern unsigned _extrue( unsigned,  unsigned long long) __attribute__((intrinsic_function(0x163, 0, "extr.u") ));
extern unsigned _extrupw( unsigned,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(0x108, 0, "extr.u") ));
extern void _fret( void) __attribute__((intrinsic_function(0x103, 0, "fret") ));
extern int _ftoi( float) __attribute__((intrinsic_function(0x105, 0, "ftoi") ));
extern int _ftoiz( float) __attribute__((intrinsic_function(0x105, 0, "ftoiz") ));
extern unsigned _ftoq31( float,  float) __attribute__((intrinsic_function(0x10b, 0, "ftoq31") ));
extern unsigned _ftoq31z( float,  float) __attribute__((intrinsic_function(0x10b, 0, "ftoq31z") ));
extern unsigned _ftou( float) __attribute__((intrinsic_function(0x105, 0, "ftou") ));
extern unsigned _ftouz( float) __attribute__((intrinsic_function(0x105, 0, "ftouz") ));
extern int _ge( int,  int) __attribute__((intrinsic_function(0x10b, 0, "ge") ));
extern unsigned _gea( unsigned*,  unsigned*) __attribute__((intrinsic_function(0x113, 0, "ge.a") ));
extern int _geu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "ge.u") ));
extern unsigned long long _imask( unsigned,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(0x137, 0, "imask") ));
extern unsigned long long _imaskcpw( const unsigned int,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(0x161, 0, "imask") ));
extern unsigned long long _imaskecpw( const unsigned int,  const unsigned int,  const unsigned int) __attribute__((intrinsic_function(0x162, 0, "imask") ));
extern unsigned long long _imaskew( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x164, 0, "imask") ));
extern void _imaskldmst( void*,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x16a, 0, "ldmst") ));
extern unsigned _insert( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x109, 0, "insert") ));
extern unsigned _inserte( unsigned,  unsigned,  unsigned long long) __attribute__((intrinsic_function(0x16c, 0, "insert") ));
extern unsigned _insnt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "insn.t") ));
extern unsigned _inst( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "ins.t") ));
extern void _isync( void) __attribute__((intrinsic_function(0x103, 0, "isync") ));
extern float _itof( int) __attribute__((intrinsic_function(0x105, 0, "itof") ));
extern unsigned long long _ixmax( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x135, 0, "ixmax") ));
extern unsigned long long _ixmaxu( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x135, 0, "ixmax.u") ));
extern unsigned long long _ixmin( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x135, 0, "ixmin") ));
extern unsigned long long _ixminu( unsigned long long,  unsigned) __attribute__((intrinsic_function(0x135, 0, "ixmin.u") ));
extern unsigned long long _ldd( void*,  const unsigned int) __attribute__((intrinsic_function(0x136, 0, "ld.d") ));
extern void _ldlcx( void*,  const unsigned int) __attribute__((intrinsic_function(0x118, 0, "ldlcx") ));
extern void _ldmst( void*,  const signed int,  unsigned long long) __attribute__((intrinsic_function(0x169, 0, "ldmst") ));
extern void _ldmstpa( void*,  const signed int,  unsigned long long) __attribute__((intrinsic_function(0x166, 0, "ldmst") ));
extern void _ldmstpb( void*,  const signed int,  unsigned long long) __attribute__((intrinsic_function(0x165, 0, "ldmst") ));
extern void _ldmstpc( void*,  const unsigned int,  unsigned long long) __attribute__((intrinsic_function(0x168, 0, "ldmst") ));
extern void _ldmstpr( void*,  unsigned long long) __attribute__((intrinsic_function(0x167, 0, "ldmst") ));
extern unsigned _ldq( void*,  int) __attribute__((intrinsic_function(0x131, 0, "ld.q") ));
extern void _lducx( void*,  const unsigned int) __attribute__((intrinsic_function(0x118, 0, "lducx") ));
extern void* _lea( void*,  const unsigned int) __attribute__((intrinsic_function(0x129, 0, "lea") ));
extern int _lt( int,  int) __attribute__((intrinsic_function(0x10b, 0, "lt") ));
extern unsigned _lta( unsigned*,  unsigned*) __attribute__((intrinsic_function(0x113, 0, "lt.a") ));
extern int _ltb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.b") ));
extern int _ltbu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.bu") ));
extern int _lth( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.h") ));
extern int _lthu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.hu") ));
extern int _ltu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.u") ));
extern int _ltw( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.w") ));
extern int _ltwu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "lt.wu") ));
extern int _madd( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "madd") ));
extern float _maddf( float,  float,  float) __attribute__((intrinsic_function(0x112, 0, "madd.f") ));
extern unsigned long long _maddhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "madd.h") ));
extern unsigned long long _maddhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "madd.h") ));
extern unsigned long long _maddhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "madd.h") ));
extern unsigned long long _maddhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "madd.h") ));
extern unsigned long long _maddmhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddm.h") ));
extern unsigned long long _maddmhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddm.h") ));
extern unsigned long long _maddmhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddm.h") ));
extern unsigned long long _maddmhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddm.h") ));
extern unsigned long long _maddmshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddms.h") ));
extern unsigned long long _maddmshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddms.h") ));
extern unsigned long long _maddmshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddms.h") ));
extern unsigned long long _maddmshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddms.h") ));
extern unsigned _maddq( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x149, 0, "madd.q") ));
extern unsigned long long _maddqe( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14a, 0, "madd.q") ));
extern unsigned long long _maddqel( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14c, 0, "madd.q") ));
extern unsigned long long _maddqell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x150, 0, "madd.q") ));
extern unsigned long long _maddqeu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14e, 0, "madd.q") ));
extern unsigned long long _maddqeuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x152, 0, "madd.q") ));
extern unsigned _maddql( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14b, 0, "madd.q") ));
extern unsigned _maddqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "madd.q") ));
extern unsigned _maddqu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14d, 0, "madd.q") ));
extern unsigned _maddquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "madd.q") ));
extern unsigned _maddrheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x148, 0, "maddr.h") ));
extern unsigned _maddrhll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "maddr.h") ));
extern unsigned _maddrhlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "maddr.h") ));
extern unsigned _maddrhul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "maddr.h") ));
extern unsigned _maddrhuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "maddr.h") ));
extern unsigned _maddrqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "maddr.q") ));
extern unsigned _maddrquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "maddr.q") ));
extern unsigned _maddrsheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x148, 0, "maddrs.h") ));
extern unsigned _maddrshll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "maddrs.h") ));
extern unsigned _maddrshlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "maddrs.h") ));
extern unsigned _maddrshul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "maddrs.h") ));
extern unsigned _maddrshuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "maddrs.h") ));
extern unsigned _maddrsqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "maddrs.q") ));
extern unsigned _maddrsquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "maddrs.q") ));
extern int _madds( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "madds") ));
extern unsigned long long _maddshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "madds.h") ));
extern unsigned long long _maddshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "madds.h") ));
extern unsigned long long _maddshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "madds.h") ));
extern unsigned long long _maddshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "madds.h") ));
extern unsigned _maddsq( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x149, 0, "madds.q") ));
extern unsigned long long _maddsqe( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14a, 0, "madds.q") ));
extern unsigned long long _maddsqel( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14c, 0, "madds.q") ));
extern unsigned long long _maddsqell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x150, 0, "madds.q") ));
extern unsigned long long _maddsqeu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14e, 0, "madds.q") ));
extern unsigned long long _maddsqeuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x152, 0, "madds.q") ));
extern unsigned _maddsql( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14b, 0, "madds.q") ));
extern unsigned _maddsqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "madds.q") ));
extern unsigned _maddsqu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14d, 0, "madds.q") ));
extern unsigned _maddsquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "madds.q") ));
extern int _maddsu( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "madds.u") ));
extern unsigned long long _maddsue( unsigned long long,  int,  int) __attribute__((intrinsic_function(0x159, 0, "madds.u") ));
extern unsigned long long _maddsuhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddsu.h") ));
extern unsigned long long _maddsuhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddsu.h") ));
extern unsigned long long _maddsuhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddsu.h") ));
extern unsigned long long _maddsuhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddsu.h") ));
extern unsigned long long _maddsumhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddsum.h") ));
extern unsigned long long _maddsumhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddsum.h") ));
extern unsigned long long _maddsumhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddsum.h") ));
extern unsigned long long _maddsumhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddsum.h") ));
extern unsigned long long _maddsumshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddsums.h") ));
extern unsigned long long _maddsumshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddsums.h") ));
extern unsigned long long _maddsumshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddsums.h") ));
extern unsigned long long _maddsumshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddsums.h") ));
extern unsigned _maddsurhll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "maddsur.h") ));
extern unsigned _maddsurhlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "maddsur.h") ));
extern unsigned _maddsurhul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "maddsur.h") ));
extern unsigned _maddsurhuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "maddsur.h") ));
extern unsigned _maddsurshll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "maddsurs.h") ));
extern unsigned _maddsurshlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "maddsurs.h") ));
extern unsigned _maddsurshul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "maddsurs.h") ));
extern unsigned _maddsurshuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "maddsurs.h") ));
extern unsigned long long _maddsushll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "maddsus.h") ));
extern unsigned long long _maddsushlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "maddsus.h") ));
extern unsigned long long _maddsushul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "maddsus.h") ));
extern unsigned long long _maddsushuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "maddsus.h") ));
extern unsigned long long _maddue( unsigned long long,  unsigned,  unsigned) __attribute__((intrinsic_function(0x159, 0, "madd.u") ));
extern int _max( int,  int) __attribute__((intrinsic_pseudo(3, "max") ));
extern unsigned _maxb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "max.b") ));
extern unsigned _maxbu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "max.bu") ));
extern unsigned _maxh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "max.h") ));
extern unsigned _maxhu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "max.hu") ));
extern unsigned _maxu( unsigned,  unsigned) __attribute__((intrinsic_pseudo(3, "max.u") ));
extern int _mfcr( const unsigned int) __attribute__((intrinsic_function(0x101, 0, "mfcr") ));
extern int _min( int,  int) __attribute__((intrinsic_pseudo(3, "min") ));
extern int _minb( int,  int) __attribute__((intrinsic_function(0x10b, 0, "min.b") ));
extern int _minbu( int,  int) __attribute__((intrinsic_function(0x10b, 0, "min.bu") ));
extern int _minh( int,  int) __attribute__((intrinsic_function(0x10b, 0, "min.h") ));
extern int _minhu( int,  int) __attribute__((intrinsic_function(0x10b, 0, "min.hu") ));
extern unsigned _minu( unsigned,  unsigned) __attribute__((intrinsic_pseudo(3, "min.u") ));
extern int _mov( int) __attribute__((intrinsic_function(0x105, 0, "mov") ));
extern void* _mova( unsigned) __attribute__((intrinsic_function(0x127, 0, "mov.a") ));
extern void* _movaa( void*) __attribute__((intrinsic_function(0x128, 0, "mov.aa") ));
extern unsigned _movd( void*) __attribute__((intrinsic_function(0x125, 0, "mov.d") ));
extern unsigned long long _movedd( unsigned,  unsigned) __attribute__((intrinsic_function(0x16b, 0, "pseudo.mov_EDD") ));
extern unsigned _movh( const unsigned int) __attribute__((intrinsic_function(0x117, 0, "movh") ));
extern void* _movha( const unsigned int) __attribute__((intrinsic_function(0x115, 0, "movh.a") ));
extern int _msub( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "msub") ));
extern unsigned long long _msubadhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubad.h") ));
extern unsigned long long _msubadhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubad.h") ));
extern unsigned long long _msubadhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubad.h") ));
extern unsigned long long _msubadhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubad.h") ));
extern unsigned long long _msubadmhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubadm.h") ));
extern unsigned long long _msubadmhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubadm.h") ));
extern unsigned long long _msubadmhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubadm.h") ));
extern unsigned long long _msubadmhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubadm.h") ));
extern unsigned long long _msubadmshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubadms.h") ));
extern unsigned long long _msubadmshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubadms.h") ));
extern unsigned long long _msubadmshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubadms.h") ));
extern unsigned long long _msubadmshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubadms.h") ));
extern long long _msubadrhll( long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "msubadr.h") ));
extern long long _msubadrhlu( long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "msubadr.h") ));
extern long long _msubadrhul( long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "msubadr.h") ));
extern long long _msubadrhuu( long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "msubadr.h") ));
extern unsigned _msubadrshll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "msubadrs.h") ));
extern unsigned _msubadrshlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "msubadrs.h") ));
extern unsigned _msubadrshul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "msubadrs.h") ));
extern unsigned _msubadrshuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "msubadrs.h") ));
extern unsigned long long _msubadshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubads.h") ));
extern unsigned long long _msubadshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubads.h") ));
extern unsigned long long _msubadshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubads.h") ));
extern unsigned long long _msubadshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubads.h") ));
extern unsigned long long _msube( unsigned long long,  int,  int) __attribute__((intrinsic_function(0x159, 0, "msub") ));
extern float _msubf( float,  float,  float) __attribute__((intrinsic_function(0x112, 0, "msub.f") ));
extern unsigned long long _msubhell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msub.h") ));
extern unsigned long long _msubhelu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msub.h") ));
extern unsigned long long _msubheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msub.h") ));
extern unsigned long long _msubheuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msub.h") ));
extern unsigned long long _msubmhll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubm.h") ));
extern unsigned long long _msubmhlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubm.h") ));
extern unsigned long long _msubmhul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubm.h") ));
extern unsigned long long _msubmhuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubm.h") ));
extern unsigned long long _msubmshll( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubms.h") ));
extern unsigned long long _msubmshlu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubms.h") ));
extern unsigned long long _msubmshul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubms.h") ));
extern unsigned long long _msubmshuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubms.h") ));
extern unsigned _msubq( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x149, 0, "msub.q") ));
extern unsigned long long _msubqe( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14a, 0, "msub.q") ));
extern unsigned long long _msubqel( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14c, 0, "msub.q") ));
extern unsigned long long _msubqell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x150, 0, "msub.q") ));
extern unsigned long long _msubqeu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14e, 0, "msub.q") ));
extern unsigned long long _msubqeuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x152, 0, "msub.q") ));
extern unsigned _msubql( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14b, 0, "msub.q") ));
extern unsigned _msubqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "msub.q") ));
extern unsigned _msubqu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14d, 0, "msub.q") ));
extern unsigned _msubquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "msub.q") ));
extern unsigned _msubrheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x148, 0, "msubr.h") ));
extern unsigned _msubrhll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "msubr.h") ));
extern unsigned _msubrhlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "msubr.h") ));
extern unsigned _msubrhul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "msubr.h") ));
extern unsigned _msubrhuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "msubr.h") ));
extern unsigned _msubrqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "msubr.q") ));
extern unsigned _msubrquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "msubr.q") ));
extern unsigned _msubrsheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x148, 0, "msubrs.h") ));
extern unsigned _msubrshll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x144, 0, "msubrs.h") ));
extern unsigned _msubrshlu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x145, 0, "msubrs.h") ));
extern unsigned _msubrshul( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x146, 0, "msubrs.h") ));
extern unsigned _msubrshuu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x147, 0, "msubrs.h") ));
extern unsigned _msubrsqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "msubrs.q") ));
extern unsigned _msubrsquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "msubrs.q") ));
extern int _msubs( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "msubs") ));
extern unsigned long long _msubse( unsigned long long,  int,  int) __attribute__((intrinsic_function(0x159, 0, "msubs") ));
extern unsigned long long _msubshell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13c, 0, "msubs.h") ));
extern unsigned long long _msubshelu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13d, 0, "msubs.h") ));
extern unsigned long long _msubsheul( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13e, 0, "msubs.h") ));
extern unsigned long long _msubsheuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x13f, 0, "msubs.h") ));
extern unsigned _msubsq( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x149, 0, "msubs.q") ));
extern unsigned long long _msubsqe( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14a, 0, "msubs.q") ));
extern unsigned long long _msubsqel( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14c, 0, "msubs.q") ));
extern unsigned long long _msubsqell( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x150, 0, "msubs.q") ));
extern unsigned long long _msubsqeu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14e, 0, "msubs.q") ));
extern unsigned long long _msubsqeuu( unsigned long long,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x152, 0, "msubs.q") ));
extern unsigned _msubsql( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14b, 0, "msubs.q") ));
extern unsigned _msubsqll( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14f, 0, "msubs.q") ));
extern unsigned _msubsqu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x14d, 0, "msubs.q") ));
extern unsigned _msubsquu( unsigned,  unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x151, 0, "msubs.q") ));
extern int _msubsu( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "msubs.u") ));
extern unsigned long long _msubsue( unsigned long long,  int,  int) __attribute__((intrinsic_function(0x159, 0, "msubs.u") ));
extern unsigned long long _msubu( unsigned long long,  int,  int) __attribute__((intrinsic_function(0x159, 0, "msub.u") ));
extern void _mtcr( const unsigned int,  int) __attribute__((intrinsic_function(0x102, 0, "mtcr") ));
extern unsigned _mul( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "mul") ));
extern unsigned long long _mule( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 2, "mul") ));
extern float _mulf( float,  float) __attribute__((intrinsic_function(0x10b, 0, "mul.f") ));
extern unsigned long long _mulmhll( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x140, 0, "mulm.h") ));
extern unsigned long long _mulmhlu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x141, 0, "mulm.h") ));
extern unsigned long long _mulmhul( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x142, 0, "mulm.h") ));
extern unsigned long long _mulmhuu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x143, 0, "mulm.h") ));
extern unsigned long long _mulmshll( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x140, 0, "mulms.h") ));
extern unsigned long long _mulmshlu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x141, 0, "mulms.h") ));
extern unsigned long long _mulmshul( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x142, 0, "mulms.h") ));
extern unsigned long long _mulmshuu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x143, 0, "mulms.h") ));
extern unsigned _mulrhll( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x153, 0, "mulr.h") ));
extern unsigned _mulrhlu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x154, 0, "mulr.h") ));
extern unsigned _mulrhul( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x155, 0, "mulr.h") ));
extern unsigned _mulrhuu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x156, 0, "mulr.h") ));
extern int _mulrqll( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x157, 0, "mulr.q") ));
extern int _mulrquu( unsigned,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x158, 0, "mulr.q") ));
extern int _muls( int,  int) __attribute__((intrinsic_function(0x10b, 2, "muls") ));
extern unsigned long long _muls_u( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "muls.u") ));
extern unsigned long long _mulue( unsigned,  unsigned) __attribute__((intrinsic_function(0x134, 2, "mul.u") ));
extern int _nand( int,  int) __attribute__((intrinsic_function(0x10b, 2, "nand") ));
extern unsigned _nandt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "nand.t") ));
extern unsigned _ne( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "ne") ));
extern unsigned _nea( unsigned*,  unsigned*) __attribute__((intrinsic_function(0x113, 2, "ne.a") ));
extern unsigned _neza( unsigned*) __attribute__((intrinsic_function(0x114, 0, "nez.a") ));
extern void _nop( void) __attribute__((intrinsic_function(0x103, 0, "nop") ));
extern unsigned _nort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "nor.t") ));
extern unsigned _not( unsigned) __attribute__((intrinsic_function(0x16d, 0, "not") ));
extern unsigned _orandnt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "or.andn.t") ));
extern unsigned _orandt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "or.and.t") ));
extern unsigned _oreq( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.eq") ));
extern unsigned _orge( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.ge") ));
extern unsigned _orgeu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.ge.u") ));
extern unsigned _orlt( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.lt") ));
extern unsigned _orltu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.lt.u") ));
extern unsigned _orne( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "or.ne") ));
extern unsigned _ornort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "or.nor.t") ));
extern unsigned _ornt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "orn.t") ));
extern unsigned _orort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "or.or.t") ));
extern unsigned _ort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "or.t") ));
extern float _pack( unsigned long long,  int) __attribute__((intrinsic_function(0x132, 0, "pack") ));
extern unsigned _parity( unsigned) __attribute__((intrinsic_function(0x105, 0, "parity") ));
extern unsigned _popcnt_w( unsigned) __attribute__((intrinsic_function(0x105, 0, "popcnt.w") ));
extern float _q31tof( float,  float) __attribute__((intrinsic_function(0x10b, 0, "q31tof") ));
extern float _qseedf( float) __attribute__((intrinsic_function(0x105, 0, "qseed.f") ));
extern void _restore( int) __attribute__((intrinsic_function(0x104, 0, "restore") ));
extern void _ret( void) __attribute__((intrinsic_function(0x103, 0, "ret") ));
extern void _rfe( void) __attribute__((intrinsic_function(0x103, 0, "rfe") ));
extern void _rfm( void) __attribute__((intrinsic_function(0x103, 0, "rfm") ));
extern void _rslcx( void) __attribute__((intrinsic_function(0x103, 0, "rslcx") ));
extern void _rstv( void) __attribute__((intrinsic_function(0x103, 0, "rstv") ));
extern int _rsub( int,  const unsigned int) __attribute__((intrinsic_function(0x10d, 0, "rsub") ));
extern int _rsubs( int,  const unsigned int) __attribute__((intrinsic_function(0x10d, 0, "rsubs") ));
extern int _rsubsu( int,  const unsigned int) __attribute__((intrinsic_function(0x10d, 0, "rsubs.u") ));
extern unsigned _satb( unsigned) __attribute__((intrinsic_function(0x105, 0, "sat.b") ));
extern unsigned _satbu( unsigned) __attribute__((intrinsic_function(0x105, 0, "sat.bu") ));
extern unsigned _sath( unsigned) __attribute__((intrinsic_function(0x105, 0, "sat.h") ));
extern unsigned _sathu( unsigned) __attribute__((intrinsic_function(0x105, 0, "sat.hu") ));
extern int _sel( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "sel") ));
extern int _seln( int,  int,  int) __attribute__((intrinsic_function(0x112, 0, "seln") ));
extern int _sh( int,  int) __attribute__((intrinsic_function(0x10b, 0, "sh") ));
extern int _sha( int,  int) __attribute__((intrinsic_function(0x10b, 0, "sha") ));
extern int _shah( int,  int) __attribute__((intrinsic_function(0x10b, 0, "sha.h") ));
extern unsigned _shandnt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.andn.t") ));
extern unsigned _shandt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.and.t") ));
extern int _shas( int,  int) __attribute__((intrinsic_function(0x10b, 1, "shas") ));
extern unsigned _sheq( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.eq") ));
extern unsigned _shge( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.ge") ));
extern unsigned _shgeu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.ge.u") ));
extern unsigned _shh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.h") ));
extern unsigned _shlt( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.lt") ));
extern unsigned _shltu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.lt.u") ));
extern unsigned _shnandt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.nand.t") ));
extern unsigned _shne( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sh.ne") ));
extern unsigned _shnort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.nor.t") ));
extern unsigned _shornt( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.orn.t") ));
extern unsigned _short( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.or.t") ));
extern unsigned _shuffle( unsigned,  const unsigned int) __attribute__((intrinsic_function(0x10d, 0, "shuffle") ));
extern unsigned _shxnort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.xnor.t") ));
extern unsigned _shxort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "sh.xor.t") ));
extern void _std( unsigned long long,  void*,  const unsigned int) __attribute__((intrinsic_function(0x13b, 0, "st.d") ));
extern void _stlcx( void*) __attribute__((intrinsic_function(0x107, 0, "stlcx") ));
extern void _stq( unsigned,  void*,  const unsigned int) __attribute__((intrinsic_function(0x13a, 0, "st.q") ));
extern void _stucx( void*) __attribute__((intrinsic_function(0x107, 0, "stucx") ));
extern int _sub( int,  int) __attribute__((intrinsic_function(0x10b, 0, "sub") ));
extern void* _suba( void*,  void*) __attribute__((intrinsic_function(0x126, 0, "sub.a") ));
extern unsigned _subb( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sub.b") ));
extern int _subc( int,  int) __attribute__((intrinsic_function(0x10b, 0, "subc") ));
extern float _subf( float,  float) __attribute__((intrinsic_function(0x10b, 0, "sub.f") ));
extern unsigned _subh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "sub.h") ));
extern int _subs( int,  int) __attribute__((intrinsic_function(0x10b, 0, "subs") ));
extern unsigned _subsh( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "subs.h") ));
extern unsigned _subshu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "subs.hu") ));
extern unsigned _subsu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "subs.u") ));
extern int _subx( int,  int) __attribute__((intrinsic_function(0x10b, 0, "subx") ));
extern void _svlcx( void) __attribute__((intrinsic_function(0x103, 0, "svlcx") ));
extern unsigned _swap_w( void*,  const signed int,  unsigned) __attribute__((intrinsic_function(0x16e, 0, "swap.w") ));
extern unsigned _swapmskw( void*,  const unsigned int,  unsigned long long) __attribute__((intrinsic_function(0x160, 0, "swapmsk.w") ));
extern void _syscall( const unsigned int) __attribute__((intrinsic_function(0x100, 0, "syscall") ));
extern void _tlbdemap( unsigned) __attribute__((intrinsic_function(0x104, 0, "tlbdemap") ));
extern void _tlbflusha( void) __attribute__((intrinsic_function(0x103, 0, "tlbflush.a") ));
extern void _tlbflushb( void) __attribute__((intrinsic_function(0x103, 0, "tlbflush.b") ));
extern void _tlbmap( unsigned long long) __attribute__((intrinsic_function(0x104, 0, "tlbmap") ));
extern void _tlbprobea( unsigned) __attribute__((intrinsic_function(0x104, 0, "tlbprobe.a") ));
extern void _tlbprobei( unsigned) __attribute__((intrinsic_function(0x104, 0, "tlbprobe.i") ));
extern void _trapsv( void) __attribute__((intrinsic_function(0x103, 0, "trapsv") ));
extern void _trapv( void) __attribute__((intrinsic_function(0x103, 0, "trapv") ));
extern unsigned long long _unpack( float) __attribute__((intrinsic_function(0x133, 0, "unpack") ));
extern void _updfl( unsigned) __attribute__((intrinsic_function(0x104, 0, "updfl") ));
extern float _utof( unsigned) __attribute__((intrinsic_function(0x105, 0, "utof") ));
extern void _wait( void) __attribute__((intrinsic_function(0x103, 0, "wait") ));
extern unsigned _xnor( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "xnor") ));
extern unsigned _xnort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "xnor.t") ));
extern unsigned _xor( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 2, "xor") ));
extern unsigned _xoreq( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.eq") ));
extern unsigned _xorge( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.ge") ));
extern unsigned _xorgeu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.ge.u") ));
extern unsigned _xorlt( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.lt") ));
extern unsigned _xorltu( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.lt.u") ));
extern unsigned _xorne( unsigned,  unsigned) __attribute__((intrinsic_function(0x10b, 0, "xor.ne") ));
extern unsigned _xort( unsigned,  const unsigned int,  unsigned,  const unsigned int) __attribute__((intrinsic_function(0x121, 0, "xor.t") ));

#endif	/* SUPPRESS_INTRINSIC_FUNCTIONS */
#endif
